export enum BalanceType {
  SUM_BALANCE = 'SUM_BALANCE',
  RECENT_SUM_BALANCE = 'RECENT_SUM_BALANCE',
  SUM_ODD_EVEN_BALANCE = 'SUM_ODD_EVEN_BALANCE',
  RECENT_SUM_ODD_EVEN_BALANCE = 'RECENT_SUM_ODD_EVEN_BALANCE',
}
