export enum FrequencyType {
  PAIR_FREQUENCY = 'PAIR_FREQUENCY',
  RECENT_PAIR_FREQUENCY = 'RECENT_PAIR_FREQUENCY',
  TRIPLET_FREQUENCY = 'TRIPLET_FREQUENCY',
  RECENT_TRIPLET_FREQUENCY = 'RECENT_TRIPLET_FREQUENCY',
}
