export enum WeightsType {
  MIN_COUNT_WEIGHTS = 'MIN_COUNT_WEIGHTS',
  TOTAL_MIN_COUNT_WEIGHTS = 'TOTAL_MIN_COUNT_WEIGHTS',
  RECENT_MIN_COUNT_WEIGHTS = 'RECENT_MIN_COUNT_WEIGHTS',
  MAX_COUNT_WEIGHTS = 'MAX_COUNT_WEIGHTS',
  TOTAL_MAX_COUNT_WEIGHTS = 'TOTAL_MAX_COUNT_WEIGHTS',
  RECENT_MAX_COUNT_WEIGHTS = 'RECENT_MAX_COUNT_WEIGHTS',
}
